name: SACAgent
config:
  make_random_actions: 0
  gamma: 0.99
  polyak: 0.995
  lr: 0.003
  alpha: 0.2
  steps_to_sample_randomly: 100 # start_steps
  checkpoint: 'models/sac/checkpoints/best_sac_local_encoder-vae_small_seed-249_episode_480.statedict'
  model_save_path: '/mnt'
  experiment_name: 'SAC_TEST_2'
  record_dir: '/mnt'
  track_name: 'Thruxton'