name: SACAgent
config:
  make_random_actions: 0
  gamma: 0.99
  polyak: 0.995
  lr: 0.003
  alpha: 0.2
  steps_to_sample_randomly: 2000 # start_steps
  checkpoint: '/mnt/SAC_VAE/best_SAC_VAE_episode_2.statedict'
  load_checkpoint: True
  model_save_path: '/mnt'
  record_dir: '/mnt'
  experiment_name: 'pixiethecat'
  track_name: 'Thruxton'
